#!/usr/bin/env python
"""
Classification Config Migration Script
=======================================

Migrates the monolithic classification_config.py (16,000+ lines, 630KB)
into a modular structure organized by legal domain.

Usage:
    python scripts/migrate_classification_config.py
    python scripts/migrate_classification_config.py --dry-run  # Preview only

This script will:
1. Read the existing classification_config.py
2. Extract CLASSIFICATION_MAP
3. Split keywords by domain prefix
4. Create domain-specific Python files
5. Update the imports in the keywords __init__.py
6. Rename the original file to classification_config_legacy.py
"""

import argparse
import re
import sys
from pathlib import Path
from collections import defaultdict
from typing import Dict, List, Any

# Add project root to path
PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))


def parse_classification_map(content: str) -> Dict[str, List[str]]:
    """
    Parse CLASSIFICATION_MAP from the config file content.

    This is a simplified parser that handles the specific format
    of the classification_config.py file.
    """
    # Find the CLASSIFICATION_MAP block
    map_match = re.search(
        r'CLASSIFICATION_MAP\s*=\s*\{(.*?)\n\}',
        content,
        re.DOTALL
    )

    if not map_match:
        print("ERROR: Could not find CLASSIFICATION_MAP in file")
        return {}

    map_content = map_match.group(1)

    # Parse each category
    classification_map = {}
    current_category = None
    current_keywords = []

    for line in map_content.split('\n'):
        line = line.strip()

        # Skip empty lines and comments
        if not line or line.startswith('#'):
            continue

        # Category header: 'Category_Name': [
        category_match = re.match(r"'(\w+)':\s*\[", line)
        if category_match:
            # Save previous category
            if current_category:
                classification_map[current_category] = current_keywords

            current_category = category_match.group(1)
            current_keywords = []
            continue

        # Closing bracket
        if line == '],':
            continue

        # Keyword: 'keyword text',
        keyword_match = re.match(r"'([^']+)'(?:,)?", line)
        if keyword_match and current_category:
            current_keywords.append(keyword_match.group(1))

    # Save last category
    if current_category:
        classification_map[current_category] = current_keywords

    return classification_map


def group_by_domain(classification_map: Dict[str, List[str]]) -> Dict[str, Dict[str, List[str]]]:
    """
    Group categories by their domain prefix.
    """
    domains = defaultdict(dict)

    for category, keywords in classification_map.items():
        # Split on first underscore
        if '_' in category:
            domain = category.split('_')[0]
        else:
            domain = 'Other'

        domains[domain][category] = keywords

    return dict(domains)


def generate_domain_file(domain: str, categories: Dict[str, List[str]]) -> str:
    """
    Generate Python file content for a domain.
    """
    lines = [
        f'"""',
        f'{domain} Law Keywords',
        f'{"=" * (len(domain) + 13)}',
        f'',
        f'Classification keywords for {domain.lower()} law domain.',
        f'Auto-generated by migrate_classification_config.py',
        f'"""',
        f'',
        f'from typing import Dict, List',
        f'',
        f'{domain.upper()}_KEYWORDS: Dict[str, List[str]] = {{',
    ]

    for category, keywords in sorted(categories.items()):
        lines.append(f"    '{category}': [")
        for keyword in sorted(keywords):
            # Escape quotes in keywords
            escaped = keyword.replace("'", "\\'")
            lines.append(f"        '{escaped}',")
        lines.append(f"    ],")

    lines.extend([
        '}',
        '',
        '',
        f'def get_{domain.lower()}_keywords() -> Dict[str, List[str]]:',
        f'    """Get all {domain.lower()} law keywords."""',
        f'    return {domain.upper()}_KEYWORDS',
        '',
    ])

    return '\n'.join(lines)


def migrate(dry_run: bool = False):
    """
    Run the migration.
    """
    source_file = PROJECT_ROOT / 'src' / 'ingestion' / 'classification_config.py'
    legacy_file = PROJECT_ROOT / 'src' / 'ingestion' / 'classification_config_legacy.py'
    keywords_dir = PROJECT_ROOT / 'src' / 'ingestion' / 'classification_config' / 'keywords'

    print(f"Reading source file: {source_file}")

    if not source_file.exists():
        print(f"ERROR: Source file not found: {source_file}")
        return 1

    content = source_file.read_text(encoding='utf-8')

    print("Parsing CLASSIFICATION_MAP...")
    classification_map = parse_classification_map(content)

    if not classification_map:
        print("ERROR: No categories found in CLASSIFICATION_MAP")
        return 1

    total_keywords = sum(len(kw) for kw in classification_map.values())
    print(f"Found {len(classification_map)} categories with {total_keywords} keywords")

    print("Grouping by domain...")
    domains = group_by_domain(classification_map)

    print(f"Found {len(domains)} domains:")
    for domain, categories in sorted(domains.items()):
        keyword_count = sum(len(kw) for kw in categories.values())
        print(f"  - {domain}: {len(categories)} categories, {keyword_count} keywords")

    if dry_run:
        print("\n[DRY RUN] Would create the following files:")
        for domain in domains:
            print(f"  - keywords/{domain.lower()}.py")
        print(f"  - Rename {source_file.name} to {legacy_file.name}")
        return 0

    # Create domain files
    print("\nCreating domain files...")
    for domain, categories in domains.items():
        domain_file = keywords_dir / f"{domain.lower()}.py"
        domain_content = generate_domain_file(domain, categories)

        print(f"  Writing {domain_file.name}...")
        domain_file.write_text(domain_content, encoding='utf-8')

    # Rename original file
    print(f"\nRenaming {source_file.name} to {legacy_file.name}...")
    if legacy_file.exists():
        print(f"  WARNING: {legacy_file.name} already exists, not overwriting")
    else:
        source_file.rename(legacy_file)

    print("\nMigration complete!")
    print("\nNext steps:")
    print("  1. Update src/ingestion/classification_config/keywords/__init__.py to import from domain files")
    print("  2. Test the application to ensure classification still works")
    print("  3. Once verified, the legacy file can be removed")

    return 0


def main():
    parser = argparse.ArgumentParser(
        description='Migrate classification_config.py to modular structure'
    )
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='Preview migration without making changes'
    )

    args = parser.parse_args()
    return migrate(dry_run=args.dry_run)


if __name__ == '__main__':
    sys.exit(main())
